// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffukdgdnywhbbalaciyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmdWtkZ2RueXdoYmJhbGFjaXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODUzMzIsImV4cCI6MjA3MTQ2MTMzMn0.JyMcw8b8e2i1W0OBCpEdPvamU4MxZOb7b84IP-yNTUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});