// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asedhoofpsfvbmwcrhfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZWRob29mcHNmdmJtd2NyaGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODI2NjQsImV4cCI6MjA3MTY1ODY2NH0.5l2072ITog4VREw8IzZPrOxCh-mvFDfyRXSFEVRUOSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});