
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './manual-types';

const SUPABASE_URL = "https://hahislsetyxbrqvgehpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhaGlzbHNldHl4YnJxdmdlaHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDk0NDUsImV4cCI6MjA3MTE4NTQ0NX0.PMTWxqTZo6HN5njnqtOVdgHjR-XffuF5sCul1LGowLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
